[workspace]
members = ["packages/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Simon Bourne <simonbourne@gmail.com>"]

[workspace.dependencies]
silkenweb = { git = "https://github.com/silkenweb/silkenweb" }
silkenweb-bootstrap = { git = "https://github.com/silkenweb/silkenweb" }
serpent-automation-frontend = { path = "packages/frontend" }
serpent-automation-executor = { path = "packages/executor" }
futures-signals = "0.3.31"
web-sys = "0.3.60"
derive_more = "0.99.17"
gloo-console = "0.2.3"
wasm-bindgen = "=0.2.87"
indoc = "2.0.3"
nom = "7.1.1"
nom-greedyerror = "0.5.0"
nom_locate = "4.0.0"
scopeguard = "1.1.0"
serde = "1.0.145"
serde_with = "3.1.0"
thiserror = "1.0.32"
tokio = "1.21.2"
gloo-net = "0.3.0"
futures = "0.3.24"
serde-json-wasm = "0.5.1"
bincode = "1.3.3"
once_cell = "1.17.1"
axum = "0.6.19"
