[package]
name = "serpent-automation-server-api"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
arpy.workspace = true
serde = { workspace = true, features = ["derive"] }
