[package]
name = "codastraea-wasm-host"
edition.workspace = true

[dependencies]
anyhow.workspace = true
wasmtime.workspace = true
walrus.workspace = true
id-arena.workspace = true
flate2.workspace = true
clonelet.workspace = true
codastraea-server-api.workspace = true
futures.workspace = true
futures-channel.workspace = true
slotmap.workspace = true
codastraea-wasm-bindings = { workspace = true, features = [
    "host-bindings",
], default-features = false }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
