[package]
name = "serpent-automation-wasm-host"
edition.workspace = true

[dependencies]
anyhow.workspace = true
wasmtime.workspace = true
walrus.workspace = true
id-arena.workspace = true
flate2.workspace = true
clonelet.workspace = true
serpent-automation-server-api.workspace = true
futures-core.workspace = true
futures-channel.workspace = true
slotmap.workspace = true

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
