[package]
name = "serpent-automation-wasm-host"
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
anyhow.workspace = true
wasmtime.workspace = true
walrus.workspace = true
id-arena.workspace = true
flate2.workspace=true
