[package]
name = "serpent-automation-executor"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
indoc = "1.0.7"
nom = "7.1.1"
nom-greedyerror = "0.4.0"
nom_locate = "4.0.0"
scopeguard = "1.1.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_with = "2.0.1"
thiserror = "1.0.32"
tokio = { version = "1.21.2", features = ["sync"] }
