[package]
name = "serpent-automation-executor"

version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "1.0.7"
nom = "7.1.1"
nom-greedyerror = "0.4.0"
nom_locate = "4.0.0"
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.32"
