[package]
name = "serpent-automation-executor"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
indoc = { workspace = true }
nom = { workspace = true }
nom-greedyerror = { workspace = true }
nom_locate = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
slotmap = { workspace = true }
futures = { workspace = true }
