[package]
name = "codastraea-frontend"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
codastraea-server-api = { workspace = true }
arpy = { workspace = true }
arpy-reqwasm = { workspace = true }
gloo-net = { workspace = true }
futures.workspace = true
once_cell = { workspace = true }
tokio = { workspace = true }
