[package]
name = "serpent-automation-frontend"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serpent-automation-executor = {workspace = true }
gloo-net = {workspace = true}
futures = { workspace = true }
gloo-console = { workspace = true }
serde-json-wasm = { workspace = true }
bincode = { workspace = true }
futures-signals = { workspace = true }
once_cell = { workspace = true }
