[package]
name = "serpent-automation-frontend"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
serpent-automation-executor = { path = "../executor" }
gloo-net = "0.2.4"
futures = "0.3.24"
gloo-console = "0.2.3"
serde-json-wasm = "0.4.1"
bincode = "1.3.3"
