[package]
name = "serpent-automation-frontend"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serpent-automation-executor = { path = "../executor" }
gloo-net = "0.2.4"
futures = "0.3.24"
gloo-console = "0.2.3"
serde-json-wasm = "0.4.1"
bincode = "1.3.3"
futures-signals = "0.3.31"
once_cell = "1.17.1"
