[package]
name = "serpent-automation-frontend"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serpent-automation-executor = { workspace = true }
serpent-automation-server-api = { workspace = true }
arpy = { workspace = true }
arpy-reqwasm = { workspace = true }
gloo-net = { workspace = true }
futures = { workspace = true }
gloo-console = { workspace = true }
futures-signals = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
clonelet = { workspace = true }
silkenweb-task.workspace = true