[package]
name = "serpent-automation-shoelace"
publish = false
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
silkenweb.workspace = true
strum = { workspace = true, features = ["derive"] }
wasm-bindgen.workspace = true
web-sys.workspace = true
