[package]
name = "serpent-automation-server"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true, features = ["ws", "headers"] }
tokio = { workspace = true, features = ["full"] }
serpent-automation-executor = { workspace = true }
bincode = { workspace = true }
