[package]
name = "serpent-automation-server"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
arpy = { workspace = true }
arpy-server = { workspace = true }
arpy-axum = { workspace = true }
axum = { workspace = true, features = ["ws", "headers"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
serde = { workspace = true, features = ["derive"] }
serpent-automation-server-api = { workspace = true }
serpent-automation-wasm-host = { workspace = true }
futures = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow.workspace = true
futures-signals.workspace = true
