[package]
name = "codastraea-wasm-guest-proc-macro"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "fold"] }
