[package]
name = "serpent-automation-wasm-guest"
edition.workspace = true

[dependencies]
crossbeam.workspace = true
inventory.workspace=true
serpent-automation-wasm-guest-proc-macro.workspace = true
