[package]
name = "serpent-automation-ui"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
silkenweb = { git = "https://github.com/silkenweb/silkenweb" }
silkenweb-bootstrap = { git = "https://github.com/silkenweb/silkenweb" }
serpent-automation-frontend = { path = "../frontend" }
serpent-automation-executor = { path = "../executor" }
futures-signals = "0.3.31"
web-sys = { version = "0.3.60", features = ["DomRect", "Element"] }
derive_more = "0.99.17"
gloo-console = "0.2.3"
wasm-bindgen = "=0.2.87"
