[package]
name = "serpent-automation-ui"
publish = false
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
silkenweb.workspace = true
silkenweb-bootstrap.workspace = true
serpent-automation-frontend.workspace = true
serpent-automation-executor.workspace = true
serpent-automation-shoelace.workspace = true
futures-signals.workspace = true
web-sys = { workspace = true, features = ["DomRect", "Element"] }
derive_more.workspace = true
gloo-console.workspace = true
wasm-bindgen.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true, features = ["sync"] }
