[package]
name = "serpent-ci-ui"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
indoc = "1.0.7"
silkenweb = { git = "https://github.com/silkenweb/silkenweb" }
serpent-ci-executor = { path = "../executor" }
futures-signals = "0.3.31"
itertools = "0.10.5"
