[package]
name = "codastraea-ui"
publish = false
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
silkenweb.workspace = true
silkenweb-signals-ext.workspace = true
codastraea-frontend.workspace = true
codastraea-server-api.workspace = true
silkenweb-ui5.workspace = true
futures-signals.workspace = true
web-sys = { workspace = true, features = ["DomRect", "Element"] }
derive_more.workspace = true
wasm-bindgen.workspace = true
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }
futures.workspace = true
