[package]
name = "serpent-automation-ui"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { git = "https://github.com/silkenweb/silkenweb", branch = "sig-newtype2-gat"}
silkenweb-bootstrap = { git = "https://github.com/silkenweb/silkenweb", branch = "sig-newtype2-gat" }
serpent-automation-executor = { path = "../executor" }
futures-signals = "0.3.31"
gloo-net = "0.2.4"
futures = "0.3.24"
gloo-console = "0.2.3"
serde-json-wasm = "0.4.1"
web-sys = {version = "0.3.60", features = ["DomRect", "Element"] }