[package]
name = "serpent-automation-ui"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { git = "https://github.com/silkenweb/silkenweb" }
serpent-automation-executor = { path = "../executor" }
futures-signals = "0.3.31"
itertools = "0.10.5"
gloo-net = "0.2.4"
futures = "0.3.24"
gloo-console = "0.2.3"
