name: website
on: 
  push:
    branches:
      - main
jobs:
  deploy-website:
    env:
      rust: beta
      ui-path: packages/ui
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ env.rust }}
        default: true
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ env.rust }}
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
    - uses: actions-rs/install@v0.1
      with:
        crate: trunk
        version: 0.16.0
    - name: Build
      working-directory: ${{ env.ui-path }}
      run: trunk build --release
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: ${{ env.ui-path }}/dist
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
